version: '3.8'

networks:
  default:

services:
  dev_sak:
    image: dev_image
    container_name: dev_sak
    build: ./docker/dev
    working_dir: /app
    volumes:
      - .:/app
      - $HOME/.config/.aws:/home/appuser/.aws:rw
      - $HOME/.terraformrc:/home/appuser/.terraformrc:ro
      - $HOME/.terraform.d:/home/appuser/.terraform.d:rw
    command: tail -f /dev/null
    entrypoint: ''
    env_file:
      - .env
    environment:
      TF_VAR_allow_ip: ${ALLOW_IP}
      TF_VAR_cloudflare_api_token: ${CLOUDFLARE_API_TOKEN}
      TF_VAR_cloudflare_zone_id: ${CLOUDFLARE_ZONE_ID}
      TF_VAR_cloudflare_zone_name: ${CLOUDFLARE_ZONE_NAME}
      TF_VAR_hcloud_token: ${HCLOUD_API_TOKEN}
    restart: always
